### ISSUE TITLE
ライセンスを確認

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#1]

**Comment by drillan** [comment]
https://github.com/quantopian/research_public

こちらにはライセンスなし

**Comment by shinseitaro** [comment]
同時にトーマスさんに確認する事

- python 2 -> python 3 などのコード変更してよいか
- ライセンス
- 未翻訳部分（英語のまま）のところは、今後翻訳予定という意味で readthedoc に載せているが問題あれば教えて下さい

**Comment by yarokoro** [comment]
上記に含まれているかもしれませんが、念の為
- JPで修正したpython3コードを本家にPRしてよいか

**Comment by shinseitaro** [comment]
+ 差分
+ 変更されたところがウェブサイトにちゃんと反映されているのか？確認
+ thomasさんをここにいれる

**Comment by shinseitaro** [comment]
トーマスさんにメール済み．まだ返事無し．
Pushして，返事がないようであれば，Forumで問い合わせる．

**Comment by shinseitaro** [comment]
トーマスさんからメール来ました。プロジェクトに関してはとても喜んでくれたようですが、返事が中途半端で

+ ライセンスに関して→The license is Creative Commons 4.0
+ Python２をPython３にプルリクを出してよいか→返答無し
+  https://github.com/quantopian/research_public/tree/master/notebooks がDocのレポジトリか？→返答無し
+ 翻訳未完成の原作を readthedocs に載せておいても大丈夫か？→返答無し

という状態でした。
これ以上突っついてもほしい返事は返ってこなさそうなので、Forumで問い合わせしますね。

**Comment by shinseitaro** [comment]
問い合わせしました。
https://www.quantopian.com/posts/japanese-translation-project-of-quantopian-documentation

**Comment by shinseitaro** [comment]
@shinseitaro 
リポジトリのライセンス - GitHub Docs
https://docs.github.com/ja/github/creating-cloning-and-archiving-repositories/licensing-a-repository
を参考にGITHUBにライセンスをつける

**Comment by shinseitaro** [comment]
https://github.com/tokyoquantopian/quantopian-doc-ja/blob/master/LICENSE 
ファイルを追加しました。Closeします。
