### ISSUE TITLE
ドキュメントのビルド方法

### ISSUE THREAD

**Issue by yarokoro** [tokyoquantopian/quantopian-doc-ja#10]
## 作業の前提
https://github.com/tokyoquantopian/quantopian-doc-ja/commit/6f105a606a249c593fd7c0f40cd2c7e93e7e3360

## 確認したいこと
- pandocがないと怒られます。事前にbrewとかでpandocをインストールしておかないとダメという認識でOKでしょうか？
  - もしそうなら、手順を含めてREADMEとかに記述しようかなと思います

## 手順
リポジトリのクローン
```
[yar ~]$ git clone https://github.com/tokyoquantopian/quantopian-doc-ja.git
[yar ~]$ cd quantopian-doc-ja
```

仮想環境の有効化
```
[yar quantopian-doc-ja]$ python3 -m venv .venv
[yar quantopian-doc-ja]$ source .venv/bin/activate
```

各種モジュールインストール
```
[yar quantopian-doc-ja]$ pip install -r requirements.txt
```

HTMLファイルの作成
```
[yar quantopian-doc-ja]$ make html
Sphinx v2.4.4 を実行中
翻訳カタログをロードしています [ja]... 完了
出力先ディレクトリを作成しています... 完了
WARNING: html_static_path '_static' が見つかりません
ビルド中 [mo]: 更新された 0 件のpoファイル
ビルド中 [html]:更新された 7 件のソースファイル
環境データを更新中[新しい設定] 7 件追加, 0 件更新, 0 件削除
ソースを読み込み中...[ 14%] index                                                                                                                                                                           ソースを読み込み中...[ 28%] lectures/Introduction_to_Python
Notebook error:
PandocMissing in lectures/Introduction_to_Python.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
http://pandoc.org/installing.html
make: *** [html] Error 2
```

**Comment by drillan** [comment]
最初は.ipynb形式のMarkdownを処理するのにpandocが必要だったかもしれませんが、現行の手順では `/notebook` ディレクトリにある.rst形式のファイルをビルドすることになったので、おそらくpandocなしでもビルドできると思います。

https://github.com/tokyoquantopian/quantopian-doc-ja/tree/master/notebooks

**Comment by yarokoro** [comment]
@drillan MakefileのSOURCEDIRでは、参照場所が違いますが、変更しないとダメということでしょうか？
https://github.com/tokyoquantopian/quantopian-doc-ja/blob/6f105a606a249c593fd7c0f40cd2c7e93e7e3360/Makefile#L8

**Comment by drillan** [comment]
> @drillan MakefileのSOURCEDIRでは、参照場所が違いますが、変更しないとダメということでしょうか？
> https://github.com/tokyoquantopian/quantopian-doc-ja/blob/6f105a606a249c593fd7c0f40cd2c7e93e7e3360/Makefile#L8

@yarokoro 設定変更は必要ないです
参考: #7

試しにissue_7ブランチでビルドしてみてください
https://github.com/tokyoquantopian/quantopian-doc-ja/tree/issue_7

**Comment by yarokoro** [comment]
@drillan ありがとうございます！
- ビルド対象は`source`で変わりない
- 現在、`source`配下はmasterブランチが`ipynb`、issue_7ブランチが`rst`形式のドキュメント

ということだったんですね。落ち着いてきたら、masterブランチは常に品質が担保されたリリース可能な成果物（ビルドが通り、チェックが完了している）が配置されると良さそうですね。
