### ISSUE TITLE
ブランチの運用方法

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#13]
## 検討時の作業スコープ
- [x] 翻訳
- [x] 査読
- [x] 日本語警察
- [x] ユーザレビュー

**Comment by yarokoro** [comment]
## 方針
- ブランチ数を最小にする
- 作業単位で情報が分散しないようにする（凝集度を高める）
- 作業況をわかりやすくする

## ブランチ一覧
- master　常にリリース可能な品質が担保されたブランチ
- Issue_# 翻訳、査読、日本語警察、ユーザレビューの作業用ブランチ

## 作業手順
1. 翻訳
   - 翻訳箇所を宣言するIssueを作成する
     - チェックボックにて、どの作業段階か分かるようにする
   - Issue_[Issue#] 形式のブランチを作成する
   - 作成したブランチに翻訳コミットを追加していき翻訳を終わらせる
   - masterブランチに対し、PR(Pull Request)を発行する
   - Issue上で査読メンバーに@mentionで通知する

2. 査読
   - PRに対して、コメントを記載していき査読を終わらせる
   - 必要に応じて、翻訳者と連絡を取り合い査読を終わらせる
   - 査読が完了したら、Issue上での日本語警察メンバーに@mentionで通知する

3. 日本語警察
   - PRに対して、コメントを記載していき日本語警察を終わらせる
   - 必要に応じて、翻訳者と連絡を取り合い日本語警察を終わらせる 
   - 日本語警察が完了したら、Issue上でのユーザレビューメンバーに@mentionで通知する

4. ユーザレビュー
   - PRに対して、コメントを記載していきユーザレビューを終わらせる
   - 必要に応じて、翻訳者と連絡を取り合いユーザレビューを終わらせる 
   - ユーザレビューが完了したら、PRをマージする

## 代替案
- 上記案だと翻訳メンバーの負荷が高そう
- Issueの代わりに、WIP(Draft) PRを使った方が良さそう？
- 進捗はチェックボックスではなく、ラベルを使うのも良さそう？
- ユーザレビューなど、マージ後に見たければブランチを追加する？
  - 日本語警察が終わった段階で、devブランチ的なものにマージする
