### ISSUE TITLE
Tutorial 2 Pipeline 翻訳

### ISSUE THREAD

**Issue by 2casa** [tokyoquantopian/quantopian-doc-ja#14]
https://github.com/tokyoquantopian/quantopian-doc-ja/tree/master/notebooks/tutorials
にはlesson1 のソースが保存されていないので、https://www.quantopian.com/tutorials/pipeline#lesson1
のページの翻訳をrstで記述していくことにします。

**Comment by 2casa** [comment]
@shinseitaro  2_pipeline_lesson1 の初稿をissue_14ブランチにコミットしました。
まだ日本語Lintなどは試していませんが、とりあえず今日の目標は達成です。

**Comment by shinseitaro** [comment]
https://github.com/tokyoquantopian/quantopian-doc-ja/pull/19
で管理しているので、この issue はクローズします
