### ISSUE TITLE
Tutorial の Clone ボタン実行に関する翻訳での説明について

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#16]
Tutorial の中で、 Clone ボタンをおしてTutorialのコードを実際に実行させる記述がある。
翻訳ではどのようにするか、決めておきたい。

Getting Startedの Lesson5 
https://www.quantopian.com/tutorials/getting-started#lesson5 
で登場したので、このように　`note` を記述して、原作ページのCloneボタンを押すように促した。

本文：

```
To run this example algorithm, create a copy by clicking the "Clone" button. Once you are in the IDE, run a backtest by clicking "Build Algorithm" (top left) or "Run Full Backtest" (top right).
``` 

翻訳：

```
"Clone" ボタンをクリックすると、IDEにコピーが作成され、アルゴリズム実行することが出来ます。

.. note:: 

    `Quantopian のドキュメント <https://www.quantopian.com/tutorials/getting-started#lesson5>`__ では、上記のように clone ボタンがありますが、翻訳ページにはありません。よって、 Quantopianにログイン後、本翻訳の原作ページ `https://www.quantopian.com/tutorials/getting-started#lesson5 <https://www.quantopian.com/tutorials/getting-started#lesson5>`__ で、 ``Clone`` ボタンを押してコードをクローンして下さい。

IDEに入ったら、"Build Algorithm" (左上) または "Run Full Backtest" (右上)をクリックしてバックテストを実行します。

```

ご意見お願いします。

**Comment by 2casa** [comment]
@shinseitaro  翻訳案で異論ありません。Tutorial2 Pipeline Lesson 12 でもアルゴリズムのクローンがあるので同じ記載にしたいと思います。

また、こういう定形の文言についてテンプレート集をWikiかなにかで管理しておくといいかも。

**Comment by shinseitaro** [comment]
@2casa 
[翻訳者作業メモ](https://github.com/tokyoquantopian/quantopian-doc-ja/wiki/%E7%BF%BB%E8%A8%B3%E8%80%85%E4%BD%9C%E6%A5%AD%E3%83%A1%E3%83%A2)に追記しました。Closeします。
