### ISSUE TITLE
【訳語】Trading Algorithm

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#20]
- 取引アルゴリズム
- トレーディングアルゴリズム

**Comment by shinseitaro** [comment]
どちらも違和感ないので、投票お願いします :bow: 

:heart: 取引アルゴリズム
:rocket: トレーディングアルゴリズム

**Comment by shinseitaro** [comment]
@fanannan 同票だったので，決めて下さい．

**Comment by fanannan** [comment]
「取引アルゴリズム」でお願いします。
トレーディングアルゴリズムでも悪くないと思いますが、訳文のリズム感からすると、ちょっと間延びする感じがしますので。

**Comment by shinseitaro** [comment]
訳語集 #36  に載せました。
Closeします。
