### ISSUE TITLE
【訳語】strategy

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#21]
- 戦略
- ストラテジー

**Comment by shinseitaro** [comment]
決めれない。投票お願いします。（最終判断は日本語警察におまかせします。 @fanannan 　)
:heart: 戦略
:rocket: ストラテジー

**Comment by shinseitaro** [comment]
@fanannan 同票だったので，決めて下さい．

**Comment by fanannan** [comment]
これもどちらでも良いと思うのですが、訳文の見やすさで「戦略」でお願いしたいと思います。

**Comment by shinseitaro** [comment]
訳語集 #36 に載せました。
Closeします。
