### ISSUE TITLE
【訳語】trading strategy

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#22]
- 取引戦略
 - トレーディングストラテジー
 - 取引ストラテジー

**Comment by fanannan** [comment]
TradingとStrategyのそれぞれの訳語と同じものの組み合わせにすれば良いと思います。

**Comment by shinseitaro** [comment]
取引戦略で決定します。
訳語集 #36 に載せました。
Closeします。
