### ISSUE TITLE
【訳語】Research

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#23]
Quantopian の Research 機能

- Research 
- リサーチ

**Comment by drillan** [comment]
一般的にカタカナにしても通じる用語なので、「リサーチ」に+1

**Comment by fanannan** [comment]
頻出する機能でもあるので、英語のままだと戸惑う可能性が高いと思います。私もカタカナに一票です。

**Comment by shinseitaro** [comment]
リサーチに決定しました。
訳語集 #36 に載せてCloseします。
