### ISSUE TITLE
【訳語】Apple（などの会社名）

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#24]
会社名はどのように表記するべきか

**Comment by shinseitaro** [comment]
会社名は、単語のままでいいと思う

**Comment by fanannan** [comment]
カタカナにしにくい、あるいは日本での知名度が低くて混乱が起きうる社名がありえること、また、社名は特定の文脈から参照されるだけで、全体に影響しないことから、私も元の英語表記のままで良いと考えます。

**Comment by shinseitaro** [comment]
「元の英語表記のまま」で決定しました
訳語集 #36 に載せてCloseします。
