### ISSUE TITLE
【訳語】query

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#26]
- クエリ
- 照会する

**Comment by fanannan** [comment]
技術用語に慣れない人には、クエリも照会もあまり通じないと思います。特に照会は、一般には意味が通じなくて問題になりやすいと思います。また、”問い合わせ”でも、「誰に？ 」という連想をされたりすると思います。
従って、どの語を選ぶべきかについては強い意見はありませんが、初出時に具体的な意味合いが分かるような丁寧な訳、ないし、注釈があれば良いかなと思います（なお、これは個別の翻訳作業の時点では忘れていていただいて結構です。日本語警察のプロセスで直せば良いと思います）。

**Comment by shinseitaro** [comment]
「日本語警察が最終的に自然な訳に治すので翻訳時は何でもよい」ということになりました。
訳語集 #36 に載せてCloseします。
