### ISSUE TITLE
【訳語】DataFrame (pandas)

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#27]
- DataFrame
- データフレーム

**Comment by drillan** [comment]
クラス名（データ型）として用いられるなら、「DataFrame」に+1
「int型」を「イント型」とは言わないので

**Comment by fanannan** [comment]
クラス名は、そのままで使うというルールで良いと思います。
ただし、組み込み型については、Pythonのドキュメント日本語訳での型名（若干統一感がないですが）に従うのが良いと思います。つまり、イント型ではなく、整数型ですね。

**Comment by shinseitaro** [comment]
「クラス名は、そのままで使う」で決定しました。
訳語集 #36 に載せてCloseします。
