### ISSUE TITLE
【訳語】historical data

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#28]
- 過去データ
- 過去のデータ
- ヒストリカルデータ

**Comment by drillan** [comment]
金融ではよく使われる用語なので、「ヒストリカルデータ」に+1
これにすると「historical volatility」なども訳しやすくなるかと

**Comment by fanannan** [comment]
”過去のデータ”とすると、誰にとってのデータなのか、例えばユーザーが過去に扱ったデータを意識させる可能性があります。”ヒストリカルデータ”ならばテクニカルタームであることが明らかに示されるので、こちらが妥当だと思います。

**Comment by shinseitaro** [comment]
「ヒストリカルデータ」に決定しました。
訳語集 #36 に載せてCloseします。
