### ISSUE TITLE
【訳語】return

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#29]
- 株価収益率
- リターン

**Comment by fanannan** [comment]
株価収益率という用語は、困ったことに色んな定義で使われてしまっており、注釈なく用いると却って混乱や誤解を招くおそれがあります。リターンも期間の概念がなく使われると多少なりとも分りにくいので、いずれを使う場合にも、計算上の定義を明確にする（本文訳文中で明確にされていれば勿論OKです）ことが必要だと思います。

**Comment by shinseitaro** [comment]
作業として「リターン」と書いて置いて、レビュアーに委ねることにします。
