### ISSUE TITLE
【訳語】asset

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#30]
- 資産
- アセット

**Comment by shinseitaro** [comment]
「株式」と訳したいところでも、 assets と表現しているところがたくさんあるので悩んでしまいます。
「資産」というと、日本語のイメージでは、自分が持っている金融資産全体の事をイメージされる事が多いように感じあまり馴染めず
「アセット」は、通常生活あまり見かけないような気がしています。

翻訳では `資産` と訳しました。

**Comment by fanannan** [comment]
株式以外に先物などもあるので、文脈によっては株式とは訳せないところもあると思います。
実務的な金融用語としては、やや意訳ですが、資産クラスという言い方もあるかもしれません。

**Comment by shinseitaro** [comment]
「資産クラス」に決定しました。
訳語集 #36 に載せてCloseします。
