### ISSUE TITLE
【金融用語】portfolio turnover

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#34]
（opt.MaxTurnover(context.max_turnover)の説明として出てきた表現）

**Comment by shinseitaro** [comment]
https://www.quantopian.com/tutorials/getting-started#lesson7 の、コードの中に出てきた表現

```python

def rebalance(context, data):
  # Retrieve alpha from pipeline output
  alpha = context.pipeline_data.sentiment_score

  if not alpha.empty:
      # Create MaximizeAlpha objective
      objective = opt.MaximizeAlpha(alpha)

      # Create position size constraint
      constrain_pos_size = opt.PositionConcentration.with_equal_bounds(
          -context.max_pos_size,
          context.max_pos_size
      )

      # Constrain target portfolio's leverage
      max_leverage = opt.MaxGrossExposure(context.max_leverage)

      # Ensure long and short books
      # are roughly the same size
      dollar_neutral = opt.DollarNeutral()

      # Constrain portfolio turnover ⇚ここ！！
      max_turnover = opt.MaxTurnover(context.max_turnover)
```

` # ポートフォリオの出来高の制約` 
と訳しています

**Comment by drillan** [comment]
> 参考: https://www.investopedia.com/terms/p/portfolioturnover.asp
> Portfolio turnover is a measure of how frequently assets within a fund are bought and sold by the managers. Portfolio turnover is calculated by taking either the total amount of new securities purchased or the number of securities sold (whichever is less) over a particular period, divided by the total net asset value (NAV) of the fund. The measurement is usually reported for a 12-month time period.

**Comment by shinseitaro** [comment]
https://www.quantopian.com/posts/issue-with-leverage#5d49c24397e6844cb31c6eb2

**Comment by shinseitaro** [comment]
https://www.quantopian.com/posts/optimize-api-maxturnover-constraint-is-it-supported

**Comment by shinseitaro** [comment]
翻訳している間にしっくりくる訳語や説明がわかるかもしれないし、Quantopian独自の使い方なのかもしれないので、
一旦、「ポートフォリオターンオーバー」という訳にしておきます。

ただし、 `|ポートフォリオターンオーバー|` という記法にしてください。
あとで差し替えを容易にする記法です。（[参照](https://sphinx-users.jp/reverse-dict/writing/replace.html)）
