### ISSUE TITLE
【訳語】tear sheet

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#35]
Quantopian の tear sheet

**Comment by shinseitaro** [comment]
[Tear sheet - Wikipedia](https://en.wikipedia.org/wiki/Tear_sheet)
によると，
> ファイナンスでは、tear sheet は企業やポートフォリオの概要を1ページにまとめたもので、時価総額やセクター、過去の株価のグラフなど、企業の現在および過去の情報が記載されています。彼らはまた、"ファンドファクトシート "または "Ditos "と呼ばれることができます。

だそうです．

ということは，訳語もティアシートでいいのでしょうか？

**Comment by fanannan** [comment]
ティアシートに一票です。

ティアシートは、良く目にするものであるにもかかわらず、あまり良く知られている言葉ではない気がします。ですが、ここでは割と重要な概念なので、ティアシートのままとするほうが、原文との関係がわかりやすく、無理に訳すよりも良いように思います。

**Comment by shinseitaro** [comment]
「ティアシート」に決定しました。
訳語集 #36 に載せてCloseします。
