### ISSUE TITLE
金融用語集

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#37]
説明が必要と思われる金融用語集

|用語|英語表現|説明例|
|---|---|---|
|流動性（が高い、低い）|(il)liquid|#39|
|ロング|long|#41|
|ショート|short|#40|
|ドローダウン|drawdown|#42|
|マーケットインパクト|market impact|#43|
|リバランス|rebalance|#44|
|ポートフォリオ|portfolio|#45|
|ポジション|position|#46|
|出来高|turnover|#47|
|エクスポージャー|exposure|#48|

**Comment by drillan** [comment]
ちなみにSphinxには `.. glossary::` というディレクティブがあります

https://www.sphinx-doc.org/ja/master/usage/restructuredtext/directives.html#glossary

これを使うと用語集が作成できます

ビルド例
https://www.sphinx-doc.org/ja/master/glossary.html

ソース
https://www.sphinx-doc.org/ja/master/_sources/glossary.rst.txt

使うかどうかは次回のmtg辺りでご相談させてください
