### ISSUE TITLE
語尾の長音

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#38]
単語の末尾に長音をつけるかどうか統一しておきたいです。

- ストラテジ
- ストラテジー

参考: [技術文書での長音記号の扱い方](http://www.yamanouchi-yri.com/yrihp/techwrt-2-4s/t-2-4s07a-1.htm)

[WEB+DB_PRESS.yml](https://github.com/tokyoquantopian/quantopian-doc-ja/blob/master/WEB%2BDB_PRESS.yml) では「サーバ」などになってるので、長音は省いたほうがやりやすいかなと思っています

**Comment by fanannan** [comment]
語尾末尾の長音については、機械的な画一化には反対です。
とりわけ、3音ルールとか日経ルール（4音基準）については、それに慣れた特定の世界の人にしか受け入れられておらず、個人的には大変抵抗感があります（出版界全般では非常に評判悪いものと認識しています）。しかし、今の時点で早急にどうすると決めて掛かるのも生産的ではないので、訳文全体を見て、必要な範囲で個別に修正する方が良いと思います。

例で言えば、ストラテジという表現は、技術用語として許されるかも知れませんが、金融用語としてはストラテジーしか見たことがありません。

**Comment by drillan** [comment]
MSなどは長音をつけているので、とりあえずは伸ばす方に統一するのはどうでしょうか（この場合はymlファイルを編集することになりますが）

https://www.atmarkit.co.jp/news/200807/25/microsoft.html

多数の単語がありそうなので、一つ一つを吟味することは現実的に厳しいのではないかと思います

**Comment by fanannan** [comment]
日本語には確立した正書法がなく、ましてや外国語からの移入語の場合にどのような表現を使うかには、色んな見解がありえます。その一方で、言葉の表現は、規格や企業がオレオレルールで決めるものではなく、それを用いる社会が現実の許容範囲を決めるものです。
言うまでもなく、常に絶対に正しいと断言できるような表現や訳語はありませんが、金融の世界の人にもPythonの世界の人にも違和感なく読める良い翻訳を目指すのであれば、個別に検討していくしかありません。そこに、わざわざ訳語を個別のイシューとして扱っている意義があると思います。
自動的にチェックできない訳語の揺れや、表現の許容範囲、統一感の確保を目指して一つ一つ吟味するのは、”日本語警察 ”担当でやりますし、それが不要ならば”日本語警察 ”の役割の意味は半減だろうと思います。そうでなければ物書きとしての職業訓練を受けた私がそれを担当する意味もありません。

**Comment by drillan** [comment]
スイマセン、うまく意図を伝えきれなかったかもしれませんが、「とりあえず」と書いたのは、なんらかの指針がないと表記ゆれを気にした際に悩むコストが都度発生することを懸念しているためです。

私自信は表記ゆれをみつけてしまうと、気になってしまい筆が遅くなるタイプなのですが、翻訳担当さんがきにせず進められるというのであれば、後回しにしてもよいかもしれません。

**Comment by fanannan** [comment]
表記揺れを揃えるのは”日本語警察”の担当だと思いますので、多少の表記揺れについては割り切って気にしないことにして、ざっくり進めてもらったら良いのではないかと思います。まあ、いずれにせよ誰から見ても完璧なものにはなりませんし、完璧に近づけるコストにも限度があると思います。
