### ISSUE TITLE
【金融用語】流動性 (liquidity)

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#39]
流動性（が高い、低い）, (il)liquid

**Comment by ToshikiUrasaki** [comment]
流動性は多くの意味があり、文脈で変わります。
ファンドの流動性といえば、多くの投資信託の場合換金性であり、現金保有率となります。一方ヘッジファンドなどは、流動性のない株式を長期保有することがあるので、換金(ポジションを売り切る)までの時間を指すこともあります。
また、株式取引のみで考えれば、トヨタなどの売買金額の大きい株式は換金しやすいので、「流動性が高い」という表現も使われます。
要(抽象的に)は、「換金のし易さ」となります。
例外は労働市場の流動性(転職のし易さ)ですが、これは割愛します。

**Comment by jazz777** [comment]
要(抽象的に)は、「換金のし易さ」となります。
を一番初めに、持ってきたほうが良いかと思いました。

初心者向けには

投資における、流動性は、資産の「換金のし易さ」となります。
現金（銀行預金）は、いつでも、好きなときに、現金可（出金）することが出来ますが
債権投資の場合は、いつでも、好きなときに、現金可（出金）出来るわけではありません。
「換金し易い」資産は「流動性が高い」
「換金し難い」資産は「流動性が低い」
現金（銀行預金）は、最も「流動性が高い」資産となります。

くらいの記載が良いのかもしれません。

＞投資信託の場合換金性であり、現金保有率
予め、X 年以内は換金できない等があるのと思います。現金保有率に依存するのであれば
問題ないと思います。

python は分かるけれど、投資は初心者対象の場合、ヘッジファンドは不要かと思いました。

**Comment by fdfpy** [comment]
jaz777さんの書き方が要点を抑えており、平易な文章で書かれているのですんなり理解できました。

**Comment by fanannan** [comment]
「換金のし易さ」は、流動性という言葉の片側について着目した表現ですね。
その反対側の、当該商品の「購入のしやすさ」について流動性という表現を使うことも多いです。『この商品は流動性が低いから、なかなか思ったような価格で、あるいは、思うように量が、買えない』というような感じですね。当該商品の取引市場に参加している買い手と売り手の数、そして、金額が多く、（ビッドアスクスプレッドが小さく）実際の約定件数が多いければ流動性が高いと言えますし、そうでなければ流動性が低い（あるいは無い）と表現します。
