### ISSUE TITLE
【金融用語】ドローダウン (drawdown)

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#42]

**Comment by ToshikiUrasaki** [comment]
最大下落幅(最大損失額)：ポートフォリオの全運用期間において一定期間(概ね1年間)で一番大きい記録となった損失幅(損失額)、ポートフォリオの潜在的な最大リスクとみなされることが多い。

**Comment by fdfpy** [comment]
内容理解できました。

**Comment by jazz777** [comment]
例があった方が分かりやすいかと思いました。

例）ドローダウン 50％
運用金額100万円の場合、100万円が50万円になったことが過去にあった事を示します。
最近の運用実績に加え、潜在的なリスクを把握する上で重要な指標となります。
