### ISSUE TITLE
【金融用語】マーケットインパクト (market impact) 

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#43]

**Comment by ToshikiUrasaki** [comment]
株式や為替などの取引において、自分の発注により市場が動いてしまう事、またはその影響の大きさ。少額取引では余りないが、機関投資家などの大口発注の場合、市場の大きさに対して、自分の注文が大き過ぎて、売り注文を出したら、自分の注文で株価を下げてしまい、結果として売り叩く(想定より売却価格が下がって約定値段が悪くなってしまう。)ことが起こること。現在は統計的に予めその影響(マーケットインパクト)を予想して、それを最小限にとどめる方法が研究されている。

**Comment by fdfpy** [comment]
内容理解できると思います。
