### ISSUE TITLE
【金融用語】リバランス (rebalance)

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#44]

**Comment by ToshikiUrasaki** [comment]
投資信託などのファンドなどが一定の期間または想定外のイベントで保有するポートフォリオの銘柄入れ替えや持ち高調整をすること。
マーケットニュートラル・ファンドは理論的には日中頻繁にリバランスを行う可能性もある。

**Comment by fdfpy** [comment]
内容理解できました。
