### ISSUE TITLE
【金融用語】ポジション (position) 

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#46]

**Comment by ToshikiUrasaki** [comment]
持ち高のこと：ロング(買い持ち)とショート(売り持ち)がある。

**Comment by fdfpy** [comment]
保有している銘柄のこと。(ポジションを減らす=保有株式を減らす)　でしょうか？

**Comment by jazz777** [comment]
ポジションの説明があった方が良いと思いました。

主に、信用取引や先物・オプション取引、外国為替取引で利用する用語。
未決済のまま残っている約定(注文）のことポジションという。
買ったままで未決済の約定（注文）の場合は、ロングポジション(買い持ち)
売ったままで未決済の約定（注文）の場合は、ショートポジション(売り持ち)
と言う
