### ISSUE TITLE
【金融用語】出来高 (turnover)

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#47]

**Comment by ToshikiUrasaki** [comment]
ある一定期間の有価証券などの金融商品の売買数量(株式の場合は特に金額ではなく株数となる)。
これに対し売買代金は売買高×売買株価となる。
個別の株式取引の場合の出来高は約定株数であるが、一日当たりの株式の出来高はその株式の活況さや人気のバロメーターとなり、取引所全体の出来高は市場規模や経済動向の活況さを意味することがある。

**Comment by shinseitaro** [comment]
はい

**Comment by fdfpy** [comment]
理解できました。問題ないと思います。

**Comment by jazz777** [comment]
一日当たりの株式の出来高はその株式の活況さや人気のバロメーターとなり、取引所全体の出来高は市場規模や経済動向の活況さを意味することがある。

分かりやすいと思います
