### ISSUE TITLE
【金融用語】エクスポージャー (exposure)

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#48]

**Comment by ToshikiUrasaki** [comment]
エクスポージャーとは元々「晒すとか曝露」の意味であったが、ポートフォリオの場合は特定の銘柄への関与率(持ち株比率）を意味する。これは特定の銘柄のリスクにも晒されるわけで、これらのリスク(株式のみならず、為替リスクや金利リスクもふくめ)への影響度がリスク・エクスポージャーである。

**Comment by fdfpy** [comment]
(1)リスクの解説が必要ではないでしょうか？リスク=株価の変動率。(日常生活の使い方と株式投資での使い方は異なる)

(2)「エクスポージャーとは元々「晒すとか曝露」の意味であったが、ポートフォリオの場合は特定の銘柄への関与率(持ち株比率）を意味する」について、説明時に具体例を挙げればいかがでしょうか。

例 　・トヨタに全資金の30%投入。
　　・ソフトバンクに全資金の20%投入。
　　・他銘柄に全資金の50%投入。　トヨタのエクスポージャーは30%である　
ということでしょうか？

(3)「これは特定の銘柄のリスクにも晒されるわけで、これらのリスク(株式のみならず、為替リスクや金利リスクもふくめ)への影響度がリスク・エクスポージャーである。」
この文章の意味がわかりません。具体例を挙げていただければわかりやすいと思います。

**Comment by ToshikiUrasaki** [comment]
ご指摘ありがとうございます！
(3)「これは特定の銘柄のリスクにも晒されるわけで、これらのリスク(株式のみならず、為替リスクや金利リスクもふくめ)への影響度がリスク・エクスポージャーである。」

これは、例えばトヨタ株であれば、輸出関連銘柄ですので、為替リスクがあります。トヨタ株が為替リスクのエクスポージャーがあると言えます。更にあるポートフォリオがトヨタ株を保有していれば、間接的ですが為替リスクへのエクスポージャーがあるとなります。

なお、蛇足ですが、外貨建て資産(米国株式など)に投資ししている円建てファンドは、保有する米国株式の株価が変動しなくても、円ドル為替が変動すれば価格変動するリスクがあるので、直接に為替リスクのエクスポージャーガあることになります。
