### ISSUE TITLE
用語（単語）の決め方

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#5]
専門用語などの単語を統一するためのプロセスを決める必要がある

GitHubのwikiで管理しようとするとこんな感じに

https://github.com/tokyoquantopian/quantopian-doc-ja/wiki/用語集

**Comment by drillan** [comment]
@shinseitaro とりあえず、wikiを編集してみて使い勝手を試してみてもらえますか？

**Comment by Kei-Sanada** [comment]
Quantopian特有の用語、trading universe、portfolio turnover、tear sheetなどはカタカナ表記
（Ex.　trading universe ならトレーディング・ユニバース）、もしくは、そのまま英語表記にするのはいかがでしょうか？

trading universeを「取引ユニバース」としても「ユニバース」に適切な日本語を考えるのに時間が掛かりそうということ。

また、今回作成する翻訳を読んで、その後、Quantopianをより深く学ぼうとする場合、英語のドキュメントを読むことになるので、カタカナ表記、英語表記の方が英語のドキュメントを読みやすいのではないかな、と思いますがいかがでしょうか。

**Comment by fanannan** [comment]
特有の用語に対して日本語訳を考えるために掛かる時間はともかくとして、できるだけ英語との対応関係を分かりやすくするのは実際的で良いと思います。カタカナ表記、あるいは、初出のカタカナ表記に注記でもとの英語の単語を付けるスタイルを支持します。英語表記を訳文のなかに直接混ぜるのには強く反対します。

**Comment by shinseitaro** [comment]
@fanannan 

具体的には 初出の場合は、`日本語 (英単語)` というイメージでしょうか？

例：

> この資産セットのことを、トレーディングユニバース（trading universe）と呼びます。トレーディングユニバースは可能な限り大きくなければなりません。

**Comment by fanannan** [comment]
@shinseitaro 

そうですね。文章から離れたところ（章末など）に注書きを記すよりも、例示していただいたように、訳語のすぐ隣に記す方が分かりやすく明確で良いと思います。

**Comment by shinseitaro** [comment]
初出/既出をどのように探すかが問題ですね。

**Comment by shinseitaro** [comment]
当議論は、 #49 で扱う事にしたのでこちらはCloseする
