### ISSUE TITLE
【訳語】quant workflow

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#52]
Quantopian が推奨しているワークフローで、彼ら独自のワークフローのようです。
[A Professional Quant Equity Workflow](https://www.quantopian.com/posts/a-professional-quant-equity-workflow)

![](https://image-proxy.quantopian.com/bd3b1bb9b4a7d65383832ad3ef72e5279f401968/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f7175616e746f7069616e5f7374617469635f6173736574732f626c6f672f63696f2d626c6f672d696d6167652d666f72756d2e706e67)

**Comment by shinseitaro** [comment]
- クォントワークフロー
- クオントワークフロー
- クォンツワークフロー
- クオンツワークフロー

**Comment by fanannan** [comment]
悩ましいですね。
Quantが単数ではありますが、クオンツワークフローが一番通じやすいのではないかと思います（英語に自信がないのですが、ここでA Professional が付いていないとすると、Quants' workflow(s)とも言えるのでしょうか？ であれば、日本語としてはクオンツで良い気もします）。

**Comment by shinseitaro** [comment]
「クオンツワークフロー」に決定しました。
訳語集 #36 に載せてCloseします。
