### ISSUE TITLE
【訳語】information coefficient 

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#53]
> The following code expresses an alpha factor based on a company's net income and market cap, and then creates an information tear sheet for that alpha factor. We will start analyzing the alpha factor by looking at it's **information coefficient** (IC). The IC is a number ranging from -1, to 1, which quantifies the predictiveness of an alpha factor. Any number above 0 is considered somewhat predictive.

**Comment by shinseitaro** [comment]
- 情報係数

**Comment by fanannan** [comment]
情報係数で良いと思います。

**Comment by shinseitaro** [comment]
「情報係数」に決定しました。
訳語集 #36 に載せてCloseします。
