### ISSUE TITLE
【金融用語】ファンダメンタルズ (fundamentals)

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#54]
ファンダメンタル分析
ファンダメンタルデータ
など。

**Comment by ToshikiUrasaki** [comment]
ファンダメンタルズとは「(経済の)基礎的条件」をいう。企業の財務状態や業績予想などの本質的価値を示し表します。
ファンダメンタル分析とは、ファンダメンタルズをもとにして、企業の本質的な価値や想定される株価を算出し、投資に利用する分析です。

なお、ファンダメンタルズは、広くは経済指標のことを指すことがあります。日本経済や世界経済全体の成長性などを指すこともあります。
