### ISSUE TITLE
【訳語】window

### ISSUE THREAD

**Issue by 2casa** [tokyoquantopian/quantopian-doc-ja#56]
【訳語案】（対象が日付や時間の場合）期間、（それ以外）区間
金融関連の書籍で、「ウィンドウ」や「窓」と訳されている文書は見かけないので、上記のような訳語案を提案します。ご意見ありましたらコメントください。

なお、Lecture 2 Pipeline Lesson3 (Factors) の以下の文章が初出だと思います。
> In Pipeline, Factors are the most commonly-used term, representing the result of any computation producing a numerical result. Factors require a column of data as well as a window length as input.

**Comment by fanannan** [comment]
2casaさんの案に賛成です。私も金融関連で「ウィンドウ」や「窓」という表現は見た記憶がありません。

**Comment by shinseitaro** [comment]
「（対象が日付や時間の場合）期間、（それ以外）区間」
に決定しました。訳語集 #36 に載せてCloseします。
