### ISSUE TITLE
【金融用語】ロング･ショート戦略 (long short trading strategy)

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#57]
#58 で訳語も issue たててます

**Comment by shinseitaro** [comment]
割安と思われる株を買い持ち、同時に割高と思われる株を売り持つ投資手法。
相場の上げ下げに左右されにくく、少しずつ収益を積み重ねることを期待する運用手法です。

通常、同業種の銘柄を組み合わせる事が多いですが（例：コカ・コーラ買い & ペプシ売り）
Quantopianの場合は、複数の銘柄を売り持ちと買い持ちに分け、多数銘柄を一度にロングショートする手法の事を `long short trading strategy` と読んでいます。

【参考】
https://www.daiwa-am.co.jp/guide/term/ra/long_1.html
https://www.sparx.co.jp/news/uploads/pdf/100806letter.pdf

**Comment by ToshikiUrasaki** [comment]
これは初心者に必要か分かりませんが、ファンドマネージャーの相場観で、ロングにチルトしたりして、その点でマーケットニュートラルと異なります。

**Comment by shinseitaro** [comment]
チルトとはなんでしょうか？

**Comment by ToshikiUrasaki** [comment]
チルトは一般向けではありませんでした。失礼しました。バイアスをかけることです。
例えばロング130億円でショート30億円という130:30みたいな傾いたポジションを作ることだったと思います。結果β=1でマーケットニュートラルとはかけ離れるのですがロング・ショートに分類されます。

**Comment by ToshikiUrasaki** [comment]
勿論ここまで極端なことをしない方が多いです。

**Comment by fdfpy** [comment]
売り持ち＝ショート,　買い持ち=ロングのことでしょうか？

**Comment by daisukeuematsu** [comment]
・全体について
fdfpyさんと同様、「ショート」「ロング」という単語と説明との対応がよく理解できませんでした。
また、「通常、同業種の銘柄を組み合わせる事が多いですが」は同業種に「割安な銘柄」と「割高な銘柄」が同時に共存することが多い、という理解でよろしいでしょうか。
・用語について
①「買い持ち」「売り持ち」
なんとなく分かるのですが「持ち」があるかないかで意味が変わる言葉で敢えて「持ち」をつけて使っているのでしょうか

**Comment by fanannan** [comment]
「持ち」をつけているのは、いずれ近いうちに反対取引をしなくてはならない立場にあるということを示唆しています。例えば株を購入した場合は、ずーーっと持っていても差し支えないので、「持ち」をつけてもつけなくても実態に差はありませんが、「買い持ち」という表現をわざわざ使うということは、それを解消しなくてはならないというニュアンスが含まれます。「売り持ち」は、（保有していた株を単に売却したのではなく）売りから入ったショートポジション（あるいは保有していた株以上に売却したショートポジション）であることを示しています。ショートポジションの維持にはコストも掛かりますし、どこかのタイミングで必ず買い戻しをしなくてはなりませんから、いずれ「持ち」状態を解消することになります。「持ち」というのは、仕舞い込んで片付けて置いてあるもの（触わる必要もなく、ずっと保管しているもの）ではなく、手に抱えてどうかしなければいけないものというイメージだと思うとわかりやすいかも知れません。
