### ISSUE TITLE
【金融用語】アウトパフォーム / アンダーパフォーム (out perform / under perform)

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#59]

**Comment by ToshikiUrasaki** [comment]
ある銘柄の収益率(騰落率)またはあるファンド基準価額やポートフォリオの収益率(騰落率)が基準となるベンチマーク(指数など)の収益率(騰落率)を上回る場合をアウトパフォームと言い、逆に下回ることをアンダーパフォームと言います。文脈にもよりますが、単純に「収益率が上回る(下回る)」の表現で良いと思います。

**Comment by fdfpy** [comment]
(1)用語について
ファンド基準価格,ポートフォリオ,指数,の解説が必要かと思います。ポートフォリオはすでに解説あり。指数は、日経225,S&P500,NWダウ等を示すと記載してあるとわかると思います。

(2)株式投資初心者に対しては、全体的に内容が理解しにくく感じます。例を挙げればどうでしょうか？　「例えば2019円1月～12月の間、7203トヨタの株価は、6364→7811(上昇率 22% ),  日経225 19561→23656(上昇率 20.9% )でしたので、トヨタの株価は日経225に対してアウトパフォームだった」でしょうか？

**Comment by daisukeuematsu** [comment]
・用語について
①ファンド基準価額
「ファンド」「基準」「価額」と３つの単語が合わさって一つの専門用語になっている単語でしょうか。また「価額」は「価格」と区別して用いるものですか。
②ポートフォリオ
業界ごとで様々な使い方をするので、ここでの厳密な意味の説明があると良いかと思います。
③ベンチマーク
上記②と同様、ここでの厳密な意味の説明があると良いかと思います。例えば、弊社（自動車系製造業）だと「（試作品等の）性能値」や「（「ベンチマーク調査」で）自社製品との競合他社との比較」などの意味で使います。
・全体について
「収益率が上回る(下回る)こと」と説明の冒頭に持ってくると分かりやすいかと思いました（←もし正しければ）
あと、アルファベット表記（例えば、ポジションだと（position）と書いてあります）の併記が無いので、統一すると良いかと思います。

**Comment by jazz777** [comment]
過去の運用実績を表現する用語。投資対象の選定にする際の、判断材料に利用するもの。
というような、前書きがあったほうが分かりやすいと思いました。

※すいません。全体的な整合性は考慮せず、全般的に初心者目安のコメントになっています。最終的な方針に従い、不要であれば、削除ください。

**Comment by ToshikiUrasaki** [comment]
> ・用語について
> ①ファンド基準価額
> 「ファンド」「基準」「価額」と３つの単語が合わさって一つの専門用語になっている単語でしょうか。また「価額」は「価格」と区別して用いるものですか。
> ②ポートフォリオ
> 業界ごとで様々な使い方をするので、ここでの厳密な意味の説明があると良いかと思います。
> ③ベンチマーク
> 上記②と同様、ここでの厳密な意味の説明があると良いかと思います。例えば、弊社（自動車系製造業）だと「（試作品等の）性能値」や「（「ベンチマーク調査」で）自社製品との競合他社との比較」などの意味で使います。
> ・全体について
> 「収益率が上回る(下回る)こと」と説明の冒頭に持ってくると分かりやすいかと思いました（←もし正しければ）
> あと、アルファベット表記（例えば、ポジションだと（position）と書いてあります）の併記が無いので、統一すると良いかと思います。

ご指摘ありがとうございます！
①ファンドと基準価額で分けられます。「基準価額」はファンドの単価です。この場合あえて「きじゅんかがく」と呼ぶ人もいます(私も証券会社でそう習いました。)。この値段を基準に売買されます。新聞の投資信託欄に掲載されている12,534みたいな数字です。
一方、基準価格は一般的に色々と使われていますので、ファンドや投資信託では使わない傾向があります。
②ポートフォリオとは、ファンドや投資信託、年金資産など様々な種類の資産を組み込んだ資金群のうちに含まれる各資産またはその資産の組み合わせのことです。結果的にファンドそのものを指すこともあります。
③ベンチマークとは市場全体を示す基準指標です。日本株ですとTOPIXと日経平均株価指数があります。またここでいう指数とは株価指数を指していますが、債券指数とか他の資産群(アセットクラス)の指数もあります。

**Comment by shinseitaro** [comment]
②のポートフォリオに関しては、QuantopianのTutorialの中では株式（ETFを含む）を指しています。このことも併せて書いておくといいかもしれません。
