### ISSUE TITLE
Python2のコード

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#6]
nbsphinx上でビルドするとエラーがでる（回避策があるかもしれない）

できればPython3に書き換えたいが、元のドキュメントにもPRしてもよさそう

**Comment by drillan** [comment]
翻訳者がコードを実行してチェックする
Python2になっているコードはPython3にしてPRを出す

**Comment by shinseitaro** [comment]
https://www.quantopian.com/posts/japanese-translation-project-of-quantopian-documentation
で Forum に 問い合わせしています。

Forumにも、トーマスさんにも、「翻訳は python3で書きます」と宣言してあるので、 python3 への書き換えに関しては問題無いと思います。
