### ISSUE TITLE
免責事項追加

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#62]

**Comment by shinseitaro** [comment]
書くべきこと
- 本翻訳を利用により生じたトラブルや損失につきましては一切責任を負わない
- 原作 https://www.quantopian.com/docs/index の内容につきましては私達が管理、運営するものではない。その内容等につきましても一切責任を負わない
- 当ウェブサイト上の情報は予告なく変更、削除される場合がある
- 翻訳成果物に記載内容については責任を負わない

**Comment by ga-su2017** [comment]
免責事項（Disclaimer）

東京 Quantopian ユーザーグループは、掲載している情報の正確性について万全を期しておりますが、その内容について保証するものではありません。
当該和訳は、英文を翻訳したものですので、和訳はあくまでも便宜的なものとして利用し、適宜、英文の原文を参照していただくようお願いします。
（英文の原文：https://www.quantopian.com/docs/index）

東京 Quantopian ユーザーグループは、間違い、情報の欠落、あるいは、掲載されている情報の使用に起因して生じる結果に対して一切の責任を負わないものとします。掲載されている全ての情報は、その時点の情報が掲載されており、完全性、正確性、時間の経過、あるいは、情報の使用に起因して生じる結果について一切の責任を負わないものとします。また、あらゆる種類の保証、それが明示されているか示唆されているかにかかわらず、また業務遂行、商品性、あるいは特定の目的への適合性への保証、また、これらに限定されない保証も含め、いかなることも保証するものではありません。

**Comment by ga-su2017** [comment]
元ネタはPwCの免責事項です。
https://www.pwc.com/jp/ja/sitemap/legal.html

**Comment by shinseitaro** [comment]
@ga-su2017 ありがとうございます！
@drillan 翻訳サイトのどこに載せるべきですかね？

**Comment by shinseitaro** [comment]
@shinseitaro 翻訳サイトトップに仮入れして、雰囲気を確かめる。

**Comment by shinseitaro** [comment]
quantopian-doc-ja/source/index.rst へ直接 `important` ディレクティブとして追記
https://github.com/tokyoquantopian/quantopian-doc-ja/compare/12f5ede2a7d8...ca8ae8184846

**Comment by shinseitaro** [comment]
翻訳サイトトップに入れました．クローズします．
