### ISSUE TITLE
最新の原稿をマージしたい

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#63]
作業中のブランチを統合してビルドした状態の原稿を確認したい

- 全体の俯瞰
- 進捗の確認
- 表記の統一

**Comment by drillan** [comment]
6/21時点の最新原稿

| ブランチ名 | ディレクトリ/ファイル | 担当 |
| -------- | -------- | -------- |
| issue_8     | https://github.com/tokyoquantopian/quantopian-doc-ja/tree/issue_8/source/tutorial     | shinseitaro     |
| issue_14     | https://github.com/tokyoquantopian/quantopian-doc-ja/tree/issue_14/source/tutorial     | 2casa     |
| tutorial3_alphalens_lesson1_to_5 | https://github.com/tokyoquantopian/quantopian-doc-ja/tree/tutorial3_alphalens_lesson1_to_5/source/tutorial     | shinseitaro     |

**Comment by drillan** [comment]
↑をマージしてビルドしたもの

https://quantopian-doc-ja-draft.readthedocs.io/ja/latest/

現状では @drillan 個人の [リポジトリ](https://github.com/drillan/quantopian-doc-ja-draft) で統合したものをGithub Actionsで実行しているので、tokyoquantopianのorganizationsに同様のリポジトリを作成する予定

**Comment by drillan** [comment]
リポジトリを作成

https://github.com/tokyoquantopian/quantopian-doc-ja-draft

**Comment by drillan** [comment]
[Read the Docs](https://readthedocs.org/projects/quantopian-doc-ja-draft/) のリポジトリを [organizationsのリポジトリ](https://github.com/tokyoquantopian/quantopian-doc-ja-draft) に変更

[設定ファイル](https://github.com/tokyoquantopian/quantopian-doc-ja-draft/blob/master/.github/workflows/draft.yml) を編集すればupdateがされるはず

**Comment by drillan** [comment]
@shinseitaro @2casa (masterにマージしていない)作業中のブランチは下記yamlファイルの ` branches["branch_name"]="source/dir_name"` の部分を修正してもらうことは可能でしょうか？

https://github.com/tokyoquantopian/quantopian-doc-ja-draft/blob/master/.github/workflows/draft.yml

**Comment by shinseitaro** [comment]
手順をここに追加しておく。
https://github.com/tokyoquantopian/quantopian-doc-ja/wiki/%E7%BF%BB%E8%A8%B3%E8%80%85%E4%BD%9C%E6%A5%AD%E3%83%A1%E3%83%A2

**Comment by shinseitaro** [comment]
追記しました。
https://github.com/tokyoquantopian/quantopian-doc-ja/wiki/%E7%BF%BB%E8%A8%B3%E8%80%85%E4%BD%9C%E6%A5%AD%E3%83%A1%E3%83%A2/_edit#4-draftyml-%E3%82%92%E6%9B%B4%E6%96%B0%E3%81%99%E3%82%8B
クローズします。
