### ISSUE TITLE
原文のnotebookを更新

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#65]
original: https://github.com/quantopian/research_public/tree/master/notebooks
リポジトリの展開先: https://github.com/tokyoquantopian/quantopian-doc-ja/tree/master/notebooks

- 原文のリポジトリの `notebook` だけを取ってくるにはsparsecheckoutでいけそう
- 更新があった場合には `git pull` する
- gitサブモジュールができるので `git submodule add` する
- pullしたnotebookは一括してreSTに変換する

**Comment by drillan** [comment]
@shinseitaro 更新があったnotebookをまるごと置き換えたいので、元の [notebooks](https://github.com/tokyoquantopian/quantopian-doc-ja/tree/master/notebooks) はごっそり消してしまって大丈夫ですか？

**Comment by drillan** [comment]
@shinseitaro スイマセン、あと1点
原文のリポジトリからサブモジュールとしてcloneしたいので、現行の `/notebooks` から `research_public/notebooks` に変えても大丈夫ですか？

**Comment by drillan** [comment]
手順を忘れそうなので、 [wiki](https://github.com/tokyoquantopian/quantopian-doc-ja/wiki/原文のnotebookの更新) に一連の手順をまとめておく

**Comment by shinseitaro** [comment]
> @shinseitaro 更新があったnotebookをまるごと置き換えたいので、元の [notebooks](https://github.com/tokyoquantopian/quantopian-doc-ja/tree/master/notebooks) はごっそり消してしまって大丈夫ですか？

はい、notebooks は消してしまって大丈夫だと思います。
翻訳はsource に入っているので問題ないかと思います。

**Comment by shinseitaro** [comment]
> @shinseitaro スイマセン、あと1点
> 原文のリポジトリからサブモジュールとしてcloneしたいので、現行の `/notebooks` から `research_public/notebooks` に変えても大丈夫ですか？

はい、OKです

**Comment by drillan** [comment]
b74d77d63f1a...cc4188977991 で対応完了

**Comment by drillan** [comment]
@shinseitaro 原文のnotebookをreSTに変換したファイルは、Gitで管理する関係で [/source_rst](https://github.com/tokyoquantopian/quantopian-doc-ja/tree/master/source_rst) にしました

原文に更新があった場合の手順は [wiki](https://github.com/tokyoquantopian/quantopian-doc-ja/wiki/原文のnotebookの更新#更新があった場合の手順) を参照してください

次回のミーティングで時間があったら軽く説明します
