### ISSUE TITLE
翻訳者作業メモを更新

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#66]
https://github.com/tokyoquantopian/quantopian-doc-ja/wiki/%E7%BF%BB%E8%A8%B3%E8%80%85%E4%BD%9C%E6%A5%AD%E3%83%A1%E3%83%A2
1. `2-ローカルの作業`の原作をコピーする部分が新しく変わっているので，更新する．
1. github のGUIが変わっているので，画像を貼り替える

**Comment by drillan** [comment]
あ、こっちのWikiに書いているのですが、場所が適切じゃなかったり、内容がわからなかったら教えてください

https://github.com/tokyoquantopian/quantopian-doc-ja/wiki/原文のnotebookの更新

**Comment by drillan** [comment]
関連 #65

**Comment by shinseitaro** [comment]
更新しました。Closeします。
