### ISSUE TITLE
Tutorialsが刷新されている

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#71]
Tutorialsの内容ががらっと変わっているので翻訳し直し中
前の版も使えるので、翻訳ドキュメントとしては残しておきたい

1. 同一プロジェクトにして、見出しを分ける
2. 前の版を別プロジェクトにして、リンクを貼る

混乱しないのは案2？

**Comment by shinseitaro** [comment]
https://github.com/tokyoquantopian/quantopian-doc-ja/pull/69 
新Tutorial１が終わったタイミングで、旧は別プロジェクトに移す
