### ISSUE TITLE
翻訳のスコープ

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#73]
[Documentation Home](https://www.quantopian.com/docs/) からの階層としては下記のようになっている

- User Guide
- API Reference
- Data Reference
- Cookbook
- Tutorials
- Lectures

確認したい内容

- 現状ではTutorialsとLecturesを対象としていて、それ以上は広げない？
  - TutorialsとLectures以外は原文のプロジェクトが見つからないので、やるにしても大変そう
- TutorialsとLecturesは同一のプロジェクトで問題なし？
  - [research_public](https://github.com/quantopian/research_public)では同じプロジェクトになっている

**Comment by shinseitaro** [comment]
#74
