### ISSUE TITLE
原文のナンバリングと翻訳の見出しの番号が一致していない

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#74]
原文ではLESSON 1やLecture 1などに番号が振られているが、Sphinxでは見出しから自動でナンバリングされるので、原文と比べようとすると混乱するかも

以下案

1. 無視する
2. 見出しの冒頭にLESSON 1やLecture 1などを付ける
3. ドキュメントの構造を原文の見出しの番号と合うように作り変える

**Comment by shinseitaro** [comment]
@drillan の余裕ができたらお願いする、という形でOKです。
