### ISSUE TITLE
HTMLドキュメントの見た目

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#75]
テーマ一覧

https://sphinx-themes.org/

現在はなんとなく `sphinxdoc` にしているが、ほかに希望があれば変更可能です

_staticにカスタマイズしたcssファイルを置くこともできるので、カスタマイズする予定があるかを決めたい( `conf.py` の扱いをどうするか)

**Comment by shinseitaro** [comment]
@drillan さんにおまかせ、という事で、いったんオープンしたまま放置。
