### ISSUE TITLE
第二回 Tutorialハッカソン準備

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#78]
- https://www.quantopian.com/lectures 
- 翻訳ではなく、原作で行う。
- （翻訳に参加してくれる人を増やすのも目的）
- 質問、疑問は 予め建てておいた Quantopian の Forum に投げてもらう（←実際の運用方法は要相談。）

内容は、

- Lecture 1 Introduction to Research A simple tutorial to help you get up to speed in the research environment.
- Lecture 2 Introduction to Python Some basic tools for working in the language.
- Lecture 3 Introduction to NumPy How to use NumPy for computing on data.
- Lecture 4 Introduction to pandas An introduction to using pandas to manage and analyze your data.
- Lecture 5 Plotting Data A brief primer.
- Lecture 6 Means Measures of centrality.
- Lecture 7 Variance Measures of dispersion.
- Lecture 8 Statistical Moments Ways to think about distributions.

5までを @drillan さん、 6以降を @2casa さんにお願いする。

- [x] 日程
- [x] コンパス
    - [x] 参加方法（ forum から clone して post する）を明記

**Comment by drillan** [comment]
> 参加方法（ forum から clone して post する）を明記

connpassのアンケートにQuantopianのユーザ名を入力してもらいましょう

**Comment by shinseitaro** [comment]
https://quantopian-tokyo.connpass.com/event/187549/
