### ISSUE TITLE
Tutorial 1 getting started  翻訳 

### ISSUE THREAD

**Issue by shinseitaro** [tokyoquantopian/quantopian-doc-ja#8]
rst ファイルで翻訳

**Comment by drillan** [comment]
@shinseitaro 一旦、仕上がりを確認したいので、このブランチのキリがよいところでmasterにマージするか、このブランチでビルドしてみてもらってもよいですか？

**Comment by shinseitaro** [comment]
@drillan はい、了解です。Lesson_1が出来たら、ビルドしてみます。 `make html` でいいんでしたっけ？

**Comment by drillan** [comment]
> @drillan はい、了解です。Lesson_1が出来たら、ビルドしてみます。 `make html` でいいんでしたっけ？

readthedocsでみんなに共有したいので、masterにマージしてpushしたら勝手にビルドが走ると思います。もしくはreadthedocsのデフォルトブランチの設定を一時的に変えてしまってもよいです。
https://readthedocs.org/dashboard/quantopian-doc/advanced/

**Comment by yarokoro** [comment]
@drillan このリポジトリのSettingsが見れないのですが、masterにpushされたら、readthedocsというところのIncoming WebHookで検知して、ドキュメンを生成するイメージですか？

**Comment by drillan** [comment]
> @drillan このリポジトリのSettingsが見れないのですが、masterにpushされたら、readthedocsというところのIncoming WebHookで検知して、ドキュメンを生成するイメージですか？

@yarokoro たぶん、メンテナーに登録されている必要があります
Read The Docsのアカウントお持ちでしたらinviteしますよ

**Comment by drillan** [comment]
現行の設定ではデフォルトブランチがmasterとなっており、pushされたら自動でビルドが走る仕組みです

**Comment by yarokoro** [comment]
GitHubと同じです。仕組みにも興味がるのでinviteお願いします。

**Comment by drillan** [comment]
@yarokoro 追加しましたー

**Comment by yarokoro** [comment]
GitHub側から POSTするのじゃなく、Read The Docsからポーリングだと理解しましたー

**Comment by yarokoro** [comment]
ポーリング形式ではなく、GitHubのSettingsでWebhooksを設定してましたー

**Comment by shinseitaro** [comment]
@yarokoro @ryoshi81 @ga-su2017 Lesson1-7 の翻訳おわりましたので査読おねがいします．

**Comment by 2casa** [comment]
@shinseitaro  Lesson7 の "Objective"  は、アルファのOptimizeに関するものなので、最適化問題の用語である「目的関数」 と訳しておけばよいのではないでしょうか？
Constraints の日本語訳は制約条件でOKです。

**Comment by ga-su2017** [comment]
気付事項はこちらに書いてよろしいのでしょうか？
pull requestsという話もあったようですが。

とりあず、lesson1
pythonのコードの下に「To use the above code copy and paste it into a new notebook in Research...」が翻訳の文章にはないようです。

**Comment by ga-su2017** [comment]
lesson2

一番上の行「Lessons 2-4 will be conducted in the Research environment....」がないようです。
体裁上別のところに書くのかもしれませんが。

Alternative Data節のリンクの個所ですが、原文は「Quantopian's Data Reference.」ですが、
翻訳では「data page」となっています。
意識的にやっているのかもしれませんが念のため。

**Comment by ga-su2017** [comment]
lesson3

・翻訳に英文が残ってしまっています。

・Universe Selection節のタイトルは翻訳というからには「ユニバースの選択」とした方が良いのかもしれません。ただアルファベットで表現するならそれでも良いと思います。全体として統一感があればよいのだと思います。

**Comment by ga-su2017** [comment]
lesson4

翻訳文にある「Dropped 1.5% entries from factor data: 」以降が原文には見当たらないようです。
必要なものなのかもしれませんが、私にはわかりませんでした。

**Comment by ga-su2017** [comment]
lesson5

訳者注・・・読者にとって有益な情報は入れたほうが良いと思います。その方が翻訳の価値が上がると思います。全体の統一感も考える必要がありそうです。

**Comment by ga-su2017** [comment]
lesson6

・英文が残っている個所があるようです。
・notnull`　のところにゴミがついているように見えます。

**Comment by ga-su2017** [comment]
lesson7

一番最後のところですが、コードのが本文の欄に入り込んでしまっているようです。

**Comment by shinseitaro** [comment]
@ga-su2017 さん、ありがとうございます！
ご指摘頂いたところを修正してプルリクエストだします。

**Comment by shinseitaro** [comment]
https://github.com/tokyoquantopian/quantopian-doc-ja/pull/17
で跡は引き継いだのでCloseする
