### ISSUE TITLE
Python2の解説になっている箇所

### ISSUE THREAD

**Issue by drillan** [tokyoquantopian/quantopian-doc-ja#80]
> https://www.quantopian.com/lectures/introduction-to-python
> Make sure that your variables are floats if you want to have decimal points in your answer. If you perform math exclusively with integers, you get an integer. Including any float in the calculation will make the result a float.

Python2の挙動を解説しており、現在の環境(Python3.5)に当てはめると誤った情報となってしまう
訳注で注釈を入れる？

**Comment by drillan** [comment]
> We can also use built-in functions to generate lists. In particular we will look at range() (because we will be using it later!). Range can take several different inputs and will return a list.

これもPython2の情報

**Comment by shinseitaro** [comment]
翻訳作業で python2 で書かれているコードは python3 に書き直しながら書いているので、
python２の挙動解説も、python3の解説に書き直してよいと思います。

ひとこと、「原作はpython2で説明されていますが、Quantopianでも現在は Python3を使っているので翻訳ではPython３で書いています」といったことを添えておくといいと思います。いかがでしょう。

**Comment by shinseitaro** [comment]
+ トップページに python ３で書いていることを明記
+ コード、翻訳内は python3 で修正する

**Comment by shinseitaro** [comment]
> トップページに python ３で書いていることを明記
@shinseitaro
