### ISSUE TITLE
サンプルコード中のQuantopian特有のAPIについて

### ISSUE THREAD

**Issue by daisukeuematsu** [tokyoquantopian/quantopian-doc-ja#81]
サンプルコードに出てくるライブラリ・APIについて、一般的に使われているものなのかQuantopian特有なものなのか、明示するか。例えばコードの中で使われているメソッドの引数でわからないものが出てきた時に、Quantopin内で調べるべきなのかインターネットで調べるべきなのか分からないのでは。

**Comment by shinseitaro** [comment]
Quantopian API reference 
https://www.quantopian.com/docs/api-reference/overview
